### ISSUE TITLE
Repository Size

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/qca-dataset-submission#267]
## Description

The size of the repository seems to be growing very large (on the order of GBs), which makes it very slow to clone on slower internet connections, and in general doesn't seem fully sustainable as larger and larger submissions are added. 

Is it worth considering moving some of the larger files to LFS rather than storing the directly in the repo? This would include large dataset and pdf files.

**Comment by dotsdl** [comment]
Agreed! Thank you @pavankum for putting together a PR for this. The problem will only continue to get worse, and this is a good time to make the change to using LFS. Unfortunately it comes at the cost of making the repo harder to use for users submitting.

**Comment by pavankum** [comment]
@dotsdl is it possible to do this task post-submission or does it still leave history behind?

**Comment by dotsdl** [comment]
Performed `git lfs` migration of `qca-dataset-submission`:

```
$ git lfs migrate import --above='10 MB' --include-ref=refs/heads/master
$ git lfs migrate import --include='*.bz2,*.zip,*.gz' --include-ref=refs/heads/master
$ git lfs migrate info --include-ref=master
migrate: Sorting commits: ..., done.                                                                                                                          
migrate: Examining commits: 100% (895/895), done.                                                                                                             
*.sdf      	267 MB	513/513 files(s)	100%
*.ipynb    	75 MB 	180/180 files(s)	100%
*.json     	69 MB 	124/124 files(s)	100%
*.pickle   	55 MB 	  17/17 files(s)	100%
*.pdf      	46 MB 	121/121 files(s)	100%

LFS Objects	3.4 GB	261/262 files(s)	100%

$ git push --force origin master

```

This rewrites history of the `master` branch on Github, and may end up breaking existing PRs.
It will almost certainly require updates to our automation to checkout LFS files involved in a PR before operating on them.

**Comment by pavankum** [comment]
I see the option "Restore branch", does it make a new PR of the closed one or it should not be used?

**Comment by dotsdl** [comment]
Still waiting to observe a size reduction. GH has to garbage collect the repo, and not clear at what frequency this is done.

**Comment by dotsdl** [comment]
Unclear how well "Restore branch" will behave. Can try it after it looks like we got our desired result here.

**Comment by dotsdl** [comment]
Okay, the repo on Github now measures 2.5GB, which is not changed from before:

```xonsh
$ json.loads($(curl --get https://api.github.com/repos/openforcefield/qca-dataset-submission))['size']/1024**2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7672  100  7672    0     0  20859      0 --:--:-- --:--:-- --:--:-- 20904
2.49521541595459
```
This size is maintained likely because I only recently removed all branches besides `master`, and GH has yet to garbage collect commits that are no longer reachable but were part of the old history.

However, to now make new submissions to the repo, users should:
1. have [git-lfs](https://git-lfs.github.com/) installed.
2. clone the repo with `GIT_LFS_SKIP_SMUDGE=1 git clone git@github.com:openforcefield/qca-dataset-submission.git` to clone without pulling LFS files; alternatively to setting `GIT_LFS_SKIP_SMUDGE=1`, can choose to [set this globally for your user on your local host](https://stackoverflow.com/questions/42019529/how-to-clone-pull-a-git-repository-ignoring-lfs#42021818).
3. use the local clone as usual to make new submissions, commit, push, make PRs. Any file with a [*.bz2,*.zip,*.gz](https://github.com/openforcefield/qca-dataset-submission/blob/00b75b73c16771baa1ea30cda6ded44f2b0077ee/.gitattributes#L84-L86) extension will automatically be added as an LFS object on commit.

Is this satisfying to folks here? The total download size for the clone is now 110.57 MiB.

**Comment by dotsdl** [comment]
Unfortunately a consequence of this procedure is any open PR you want merged will need to be re-created. You *must* create this from a fresh clone of this repo, with the new `master` branch. 

The automation should still be able to operate on existing merged PRs because it only cares about the file paths in those PRs held on to by GH, not the history, so we should be operationally okay there. I will check next if we need to update the GH Actions themselves to include installs of `git-lfs` so the artifacts the Actions must operate on are actually present.

**Comment by pavankum** [comment]
@dotsdl Great work! :raised_hands: Can you please post the same on slack channel as well to notify other users of the changes.

**Comment by dotsdl** [comment]
Will do next; in sprint planning but will post for all after.

**Comment by j-wags** [comment]
I see we're getting billed for git LFS (and have been getting billed, because of protein-ligand-benchmarks). 

Can you tell whether the bandwidth is counted BOTH for uploads AND downloads? Do downloads on GH Actions (like error cycling) count against the count?) 

<img width="985" alt="Screen Shot 2022-02-23 at 1 23 56 PM" src="https://user-images.githubusercontent.com/16329175/155411108-ca7de2e3-82f1-49e8-af70-87bef2e83416.png">

**Comment by dotsdl** [comment]
Addressed bandwidth usage with [an action that caches LFS objects on checkout](https://github.com/openforcefield/qca-dataset-submission/commit/8aea2289ecad472286560e5407c846aa37ec6bc7).

**Comment by dotsdl** [comment]
Think we've got this one addressed. Closing for now, feel free to reopen if there are outstanding issues with what we've done.
